# This workflow will publish a Python package to PyPI when a push event occurs on the 
# main branch.

name: Publish package

on:
  push:
    branches:
      - main

jobs:
  publish: 

    # Configure the publish job variables
    strategy:
      matrix:
        python-version: ['3.10']
        poetry-version: ['1.7.1']
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry ${{ matrix.poetry-version }}
        env:
          POETRY_VERSION: ${{ matrix.poetry-version }}
          POETRY_VIRTUALENVS_CREATE: true
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Publish package
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}
          poetry publish --build

